### PR TITLE
Sync with vulkan-wip branch

### PR DESCRIPTION
**Pull request by kd-11**

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Why vulkan not works with Nvidia ?

**Comment by kd-11** [comment]
Do the lunarg samples work for you? Install the SDK and check.

**Comment by Zangetsu38** [comment]
What sdk ? link for this please ? :)

**Comment by kd-11** [comment]
https://vulkan.lunarg.com/signin
Do not register, just click the link for windows at the bottom. Once it installs, you will find some demos in C:\VulkanSDK\bin e.g cube.exe. Try running that and see if it works. Also, try running vulkaninfo and check output that will be installed by the sdk.

**Comment by Zangetsu38** [comment]
ok thx :)

**Comment by Zangetsu38** [comment]
Cube works 
cube
But rpcs3 show this after launch any games 
error

**Comment by kd-11** [comment]
Does rpcs3 run the basic triangle test and the cube test?

**Comment by kd-11** [comment]
@Zangetsu38 Could you also send me the output of vulkaninfo? It may be helpful to see what extensions nvidia supports right now.

**Comment by Zangetsu38** [comment]
look output here https://gist.github.com/Zangetsu38/5845e6fb97eaa52d5a07
and test cube or other same error

**Comment by kd-11** [comment]
@Zangetsu38 try setting all debug layers to on
https://github.com/kd-11/rpcs3/blob/vulkan/rpcs3/Emu/RSX/VK/VKHelpers.h#L18-L18
Change 0 to 9
Does the vulkan window pop up, or does it crash immediately on launch?

**Comment by Zangetsu38** [comment]
exactly same error and i have updated driver 356.45

**Comment by kd-11** [comment]
@Zangetsu38 Is there anything in rpcs3.log? If not the vulkan driver is not loading properly. I'll have to provide a special branch to debug that for you.

**Comment by Zangetsu38** [comment]
end log indicate only this 

> ·! MEM: Thread Local Storage initialized (g_tls_start=0x24b000, user_size=0x110)
> **\* TLS segment addr: 0x000816a0
> **\* TLS segment size: 0x00000004
> ·! Stopping emulator...
> ·! All threads signaled...
> ·! {PPU Thread[0x1](main_thread)[0x00247008]} Thread aborted
> ·! All threads stopped...
> ·! Objects cleared...
> ·! Stopping emulator...

**Comment by kd-11** [comment]
I'll write a version with meaningful debug messages and checks and see if it at least starts on nvidia.

**Comment by Zangetsu38** [comment]
ok :)

**Pull request merged**
